### ISSUE TITLE
MiFare cards?

### ISSUE THREAD

**Issue by datapolitical** [Hamspiced/NFC-Resonant-Frequency-Amplifier#1]
My transit card is a classic MiFare card operating at 13.56, but with a rectangular antenna. I’m hoping your extender will work with that so my card can be reliably read from inside my wallet. Will that work?

https://www.bidnetdirect.com/pennsylvania/solicitations/open-bids/statewide/Contactless-Smart-Fare-Media/443110149596

**Comment by Hamspiced** [comment]
Hey Chris!

So i saw this email come through last week when i was on a walk with my daughter.  I planned to reply to it when i got home but life got in the way.  I then couldnt find it because i didnt know through what way i was being contacted so i couldnt figure out where the notification came from.

So IF you card is operating at 13.56 then yes, throwing one of these stickers on your wallet will work.  I wouldnt say putting it on the card directly will affect it as much as putting distance between the sticker and the card itself.  You need to create some space between the transponder and the circuit to get the best performance.  

This is dependant upon the card and reader actually being 13.56mhz.  The link you submitted states that it uses an HID Compliant reader at 125khz which this device will not work at.  I am in the early stages of testing LF 125khz circuits so im not yet ready for a production run.  hopefully soon though.
